version: '3'
services:
    mongodb:
        container_name: edureka_mongo_db
        image: mongo
        volumes:
          - dbdata:/data/db
        ports:
          - "27017:27017"
        restart: unless-stopped
        networks:
          - edurekanet
    admin:
        container_name: edureka_admin_app
        image: shikha1105/edureka_admin_app
        restart: always
        environment:
          - db_service_name=edureka_mongo_db
          - mongo_port=27017
          - db_name=db_edureka
        links:
          - mongodb
        ports:
          - "9900:9900"
        networks:
          - edurekanet

    cust:
        container_name: edureka_customer_app
        image: shikha1105/edureka_customer_app
        restart: always
        environment:
          - db_service_name=edureka_mongo_db
          - mongo_port=27017
          - db_name=db_edureka
        links:
          - mongodb
        ports:
          - "9901:9901"
        networks:
          - edurekanet

    reverseproxy:
        container_name: edureka_nginx_server
        image: shikha1105/edureka_nginx_server
        ports:
          - "80:8080"
        networks:
          - edurekanet

networks:
  edurekanet:
    driver: bridge

volumes:
  dbdata: